resources:
  - name: python_app
    type: GitRepo
    configuration:
      gitProvider: ranjithr_github
      path: ranjithrs/python_example
      branches:
        include: master
  - name: python_app_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: python-app
      buildNumber: 1      

pipelines:
  - name: python_pipeline
    steps:
      - name: build
        type: Bash
        configuration:
          inputResources:
            - name: python_app
          integrations:
            - name: art
        execution:
          onExecute:
            - pushd $res_python_app_resourcePath
            - python setup.py sdist
            - pwd
            - jfrog rt u dist/python-example-0.1.tar.gz python-local
            
